Bug eci 222 add abandoned cart test
DripEmail/magento-m2-extension pull request #50
Opened 2019-12-27 22:26 UTC by starshine1510

Ported over the abandoned cart test to M2 since we added it to M1.
Abandoned cart url doesn't seem to work the same as M1.
Visiting an abandoned cart url takes you to an empty shopping cart.
Not sure if this is due to how M2 handles sessions or if we are manipulating the cart url incorrectly.
We should look into why but for now the test is in place even though I don't think the results are what we really want.  I'm out of ideas at this point.

2019-12-30 14:48 UTC, will-in-wi requested changes
Could you delete the `devtools_m2/git` file? It doesn't seem needed.

I agree that this test is a net positive even if we don't have the same functionality in M1 and M2. However, I'd really like to have us dig into this, or at least throw a ticket onto the backlog to do so. I'm a little nervous that we're going to have a customer upgrade from M1 to M2 and then be surprised when we don't have this feature.

2019-12-30 14:48 UTC, will-in-wi commented on devtools_m2/cypress/integration/CustomerCartInteractions/steps.js
> +      console.log('In simple case')
Could we drop the console.log or convert it to https://docs.cypress.io/api/commands/log.html#Syntax ?

2019-12-30 14:48 UTC, will-in-wi commented on devtools_m2/cypress/integration/CustomerCartInteractions/steps.js
> +
I really want to add a proper linter to these files. Pending that, could this newline be deleted?

2019-12-30 15:45 UTC, tdieterich-drip approved these changes

2020-01-17 20:19 UTC, iantance commented
@starshine1510 Looks like we were attempting to build the cart by clearing the current cart's item and then merging the items from their abandoned cart. But when the current cart _is_ the abandoned cart, we end up with an empty cart.

2020-01-21 16:08 UTC, will-in-wi approved these changes

2020-01-21 21:06 UTC, merged